name: "The Open Blog"
description: "Mihnea DB's blog. Mostly technical stuff."
url: http://www.mihneadb.net

markdown: rdiscount

destination: ./_site/post
permalink: /post/:title
highlighter: pygments

